### ISSUE TITLE
0.1.7好像又不能用了

### ISSUE THREAD

**Issue by crylcy** [pizzamx/zimuku_for_kodi#11]
大佬，如题。这字幕库反扒咋动不动更新呢。。。

**Comment by pizzamx** [comment]
这下似乎真的验证验证码了

**Comment by crylcy** [comment]
...好吧，谢谢大佬

**Comment by hq2636** [comment]
大佬有啥办法没，0.17到现在一直没法用啊

**Comment by pizzamx** [comment]
> 大佬有啥办法没，0.17到现在一直没法用啊

水平不行，不会搞验证码

**Comment by scillidan** [comment]
等于是无差别防御了，全部先墙了再说，估计被爬的厉害。但它是每次你都要验证，严重影响使用体验了…
你说你可以不用…但你已经收了这么多资源，发布人也养成跑这里发的习惯了。（这也是被爬的原因）

但预计，这么多用户，一定有人先受不了了。跑工信局报备和举证，你这个在黑色地带，被墙概率相当大。
又因为这个验证实在太烦，不被同情。

用户估计就是跟着发布者迁移，目前还未见有下一个迁徙地。
到那时，这件事和这个网站也会这么过去…
估计时辰快到了

**Comment by pizzamx** [comment]
我手工一般是用 SubHD…

**Comment by scillidan** [comment]
记得SubHD，还以为挂了，原来还在。这下我没意见了

**Comment by jiangpengcheng** [comment]
似乎又解除验证码了

**Comment by pizzamx** [comment]
works again, please manually update to v0.1.8 if you really need this
