### ISSUE TITLE
建议搜索字段除了名字可以再加个年份

### ISSUE THREAD

**Issue by fsi044689** [pizzamx/zimuku_for_kodi#13]
光是用名字搜索很容易搜到其他名字相似影片的字幕。我自己本地修改个搜索代码在querystring后面空格在加个元数据年份。搜索准确率会高很多

**Comment by fsi044689** [comment]
![image](https://user-images.githubusercontent.com/16712429/203543434-5c828642-ed33-4b23-9fbf-173407c28418.png)

**Comment by pizzamx** [comment]
哦，那你提个 PR 呗

**Comment by pizzamx** [comment]
included in v 0.1.9
