### ISSUE TITLE
字幕库好像也开启验证码了...

### ISSUE THREAD

**Issue by Nikkiiw** [pizzamx/zimuku_for_kodi#16]
![image](https://user-images.githubusercontent.com/91337184/225245732-99121757-30c2-4e2b-977f-d3aa81053c9c.png)

🤦‍♂️

**Comment by pizzamx** [comment]
不是「也」，是「又」…让我们期待关闭的那天！

**Comment by Nikkiiw** [comment]
是的，应该用“又”！感谢回复！

**Comment by Nikkiiw** [comment]
😁

**Comment by spqrk** [comment]
1、插件能做到弹窗kodi吗，把验证码展示到弹窗里，然后再弹个输入框，手动输入验证码，不知道是否可行，原来的search url的返回值倒是把base64格式的图片返回了
2、再就是部署个ddddocr的服务api给插件去调用，稍微修改下查询的代码结构（我改了下代码然后结合我nas部署的ddddocr服务现在倒是可用）

**Comment by pizzamx** [comment]
> 1、插件能做到弹窗kodi吗，把验证码展示到弹窗里，然后再弹个输入框，手动输入验证码，不知道是否可行，原来的search url的返回值倒是把base64格式的图片返回了 2、再就是部署个ddddocr的服务api给插件去调用，稍微修改下查询的代码结构（我改了下代码然后结合我nas部署的ddddocr服务现在倒是可用）

1 不会
2 要求客户端部署？这不大现实吧…

**Comment by spqrk** [comment]
1的话，我查看了文档，找到了数字输入框xbmcgui.Dialog().numeric(type, heading[, defaultt, bHiddenInput])，但是图片展示框的函数没找到
2的话只能是想继续用的自己本地部署了，让你搞个公共的代价就太大了哈哈

**Comment by spqrk** [comment]
另外想问下那个xbmcgui库去哪里下载，上次下载的找不到了

**Comment by spqrk** [comment]
尝试做了一部分，拿到验证码之后找不到支持的kodi弹窗控件展示验证码，卡住了emmm

**Comment by pizzamx** [comment]
> 尝试做了一部分，拿到验证码之后找不到支持的kodi弹窗控件展示验证码，卡住了emmm

我寻思应该也不大难，毕竟那验证码很土，只是我水平实在太低……

**Comment by spqrk** [comment]
koid的支持不太好，展示不出来验证码

**Comment by pizzamx** [comment]
hail to @lm317379829
