### ISSUE TITLE
暂时可用方案

### ISSUE THREAD

**Issue by spqrk** [pizzamx/zimuku_for_kodi#17]
使用了百度ocr，每月可使用1000次识别，鉴于字幕库验证过一次之后，一段时间内不会重复验证，1000次够使用一个月了，
此版本缺陷在于需要输入百度ocr的access_token，并且配置到zimukux的配置选项中

![微信图片_20230517224124](https://github.com/pizzamx/zimuku_for_kodi/assets/16741994/461135f8-adde-49ff-b5ea-845d82994711)

至于百度的ocrToken怎么获取，看下面，
step1: 登录百度开发网站，到下面这个页面https://console.bce.baidu.com/ai/?fromai=1#/ai/ocr/overview/index
点击下图的领取免费资源按钮
![1684462076245](https://github.com/pizzamx/zimuku_for_kodi/assets/16741994/79e98aa0-022c-4449-93d5-2ab94053d810)
之后勾选通用场景ocr，然后点击下面的0元领取

step2：配置应用获取appKey等信息，到https://console.bce.baidu.com/ai/?fromai=1#/ai/ocr/app/list这个地址，新建一个应用，信息随便写，需要个人实名认证，之后记下应用的API Key与Secret Key
![网页捕获_19-5-2023_10109_console bce baidu com](https://github.com/pizzamx/zimuku_for_kodi/assets/16741994/820265eb-1b4e-4494-b938-3f8814c20dea)

step3：到下面的地址填上你上一步保存的API Key与Secret Key，获取一个access_token,这个token就是你要配置到插件的token
地址：https://console.bce.baidu.com/tools/#/api?product=AI&project=%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB&parent=%E9%89%B4%E6%9D%83%E8%AE%A4%E8%AF%81%E6%9C%BA%E5%88%B6&api=oauth%2F2.0%2Ftoken&method=post
![1684462467036](https://github.com/pizzamx/zimuku_for_kodi/assets/16741994/6e0d42db-9fd2-4151-b621-2b4bb8b63608)
信息填写完之后，点击上面的调试按钮，就可以获取到token，如图
![1684462555884](https://github.com/pizzamx/zimuku_for_kodi/assets/16741994/73cdbb6d-4020-474a-b196-cc055772b367)

打包好版本百度云地址：
链接: https://pan.baidu.com/s/1Cku1XlbmI2iK66n9-ozArA?pwd=hyye 提取码: hyye 

上面的插件需要在插件中配置百度assecc_token   不然无法使用

**Comment by lm317379829** [comment]
在你的基础上改了ocr服务器为我的公益服务器，更新了一些bug。
不需要百度ocr了。
下载地址：https://cjk.lm317379829.repl.co/CJK/repo/script.subtitles.zimukux/script.subtitles.zimukux-0.1.9.zip

**Comment by pizzamx** [comment]
Kodi 不让我 merge 进去，因为调用第三方 API 了…
