### ISSUE TITLE
支持Kodi20以上

### ISSUE THREAD

**Issue by itscolor** [pizzamx/zimuku_for_kodi#19]
如题:开发者，何时打算支持一下最新版本的KODI.

**Comment by pizzamx** [comment]
不能用吗？

**Comment by itscolor** [comment]
> 不能用吗？

安装失败

**Comment by zjn9011** [comment]
可以用啊，Android tv 9 +kodi20.1一切正常

**Comment by itscolor** [comment]
> 可以用啊，Android tv 9 +kodi20.1一切正常

我用的魔改版本，支持杜比视界的版本KodiV21. 链接：https://repo.kodinerds.net/index.php?action=list&scope=all&version=omega/

**Comment by lm317379829** [comment]
> > 可以用啊，Android tv 9 +kodi20.1一切正常
> 
> 我用的魔改版本，支持杜比视界的版本KodiV21. 链接：https://repo.kodinerds.net/index.php?action=list&scope=all&version=omega/

把安装失败的log贴出来，估计是api有变化。
