### ISSUE TITLE
字幕库域名变了，又挂了

### ISSUE THREAD

**Issue by crylcy** [pizzamx/zimuku_for_kodi#24]
好像换成了srtku.com

**Comment by pizzamx** [comment]
又换成验证码了，得用回 0.2.0，不过老哥的验证码服务似乎不能用了……

**Comment by crylcy** [comment]
🤣👍👍👍辛苦了大佬

pizzamx ***@***.***> 于 2024年2月19日周一 22:15写道：

**Comment by ccxp** [comment]
0.2.0验证可用，用腾讯云ocr搞了个服务验证了一下

**Comment by crylcy** [comment]
> 0.2.0验证可用，用腾讯云ocr搞了个服务验证了一下

直接用还是怎么用腾讯云ocr呀，请指点。

**Comment by ccxp** [comment]
> > 0.2.0验证可用，用腾讯云ocr搞了个服务验证了一下
> 
> 直接用还是怎么用腾讯云ocr呀，请指点。

https://github.com/ccxp/ocr_for_zimukux
写了个简单的go服务，需要自己去开通腾讯云ocr权限，1个月免费1000次，自己用完全够了。

**Comment by crylcy** [comment]
> > > 0.2.0验证可用，用腾讯云ocr搞了个服务验证了一下
> > 
> > 
> > 直接用还是怎么用腾讯云ocr呀，请指点。
> 
> https://github.com/ccxp/ocr_for_zimukux 写了个简单的go服务，需要自己去开通腾讯云ocr权限，1个月免费1000次，自己用完全够了。 启动后，在0.2.0的ocr url里面，配上 http://ip:port/ocr

大神威武！多谢

**Comment by pizzamx** [comment]
这个分支支持百度的 OCR 服务：https://github.com/pizzamx/zimuku_for_kodi/tree/v0.2.0b
