### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by HysenX-LI** [pizzamx/zimuku_for_kodi#26]
作者呀，是不是现在由于字幕库每次进去都要输入个验证码，所以插件用不了了

**Comment by pizzamx** [comment]
用 0.2.0b 可以调用百度验证码服务解决

Li Hongyi ***@***.***> 于 2024年9月7日周六 下午10:07写道：

**Comment by HysenX-LI** [comment]
好的好的，谢谢，我试试
