### ISSUE TITLE
是不是又挂了

### ISSUE THREAD

**Issue by zohucen** [pizzamx/zimuku_for_kodi#6]

**Comment by zohucen** [comment]
> 呃，网站上验证码了

大概看了下，需要验证码过后带着认证的cookie

**Comment by zohucen** [comment]
可不可以来个曲线救国， 弄个接口，插件请求网页的时候，先从接口获取cookie，再带着cookie去请求。 
每三天手动更新一下cookie值

**Comment by pizzamx** [comment]
感觉没啥意义，如果网站铁了心要防扒，那肯定搞不过他吧。哎……
