### ISSUE TITLE
不管用

### ISSUE THREAD

**Issue by benny1900** [pizzamx/zimuku_for_kodi#8]
昨天试了0.1.5，搜不到字幕。今天更新0.1.6，有的视频搜得到，有的搜不到（在网页上可以搜到）

**Comment by pizzamx** [comment]
> 昨天试了0.1.5，搜不到字幕。今天更新0.1.6，有的视频搜得到，有的搜不到（在网页上可以搜到）

哪个搜不到，我试试看

**Comment by benny1900** [comment]
> > 昨天试了0.1.5，搜不到字幕。今天更新0.1.6，有的视频搜得到，有的搜不到（在网页上可以搜到）
> 
> 哪个搜不到，我试试看

用halo.s01e09.1080p.web.h264-cakes在网页上可以搜到5个结果，但是插件里搜不到。视频文件的全名是halo.s01e09.1080p.web.h264-cakes.mkv，用文件全名在网页上搜索的话，结果也是0个

**Comment by pizzamx** [comment]
不是用文件名搜，你看看日志，是用「tvshow」那个变量的值搜的

> > > 昨天试了0.1.5，搜不到字幕。今天更新0.1.6，有的视频搜得到，有的搜不到（在网页上可以搜到）
> > 
> > 
> > 哪个搜不到，我试试看
> 
> 用halo.s01e09.1080p.web.h264-cakes在网页上可以搜到5个结果，但是插件里搜不到。视频文件的全名是halo.s01e09.1080p.web.h264-cakes.mkv，用文件全名在网页上搜索的话，结果也是0个

**Comment by benny1900** [comment]
明白了
