### ISSUE TITLE
字幕能搜索到但是总是下载失败

### ISSUE THREAD

**Issue by wjw054509** [pizzamx/zimuku_for_kodi#9]
字幕可以通过插件搜索到，但是无法下载

**Comment by pizzamx** [comment]
> 字幕可以通过插件搜索到，但是无法下载

升级到 0.1.6 了吗？

**Comment by pizzamx** [comment]
玩球蛋，今天不行了……

**Comment by pizzamx** [comment]
fixed in v0.1.7

**Comment by wjw054509** [comment]
> fixed in v0.1.7

0.1.7还是显示下载失败

**Comment by pizzamx** [comment]
> > fixed in v0.1.7
> 
> 0.1.7还是显示下载失败

我的环境已经没问题了，不然你开 debug 把日志贴上来看看

**Comment by wjw054509** [comment]
![20220618_234959.jpg](https://user-images.githubusercontent.com/85219784/174446699-a08d7930-14ec-4ccc-a032-6a1d64d31d92.jpg)![20220618_235009.jpg](https://user-images.githubusercontent.com/85219784/174446703-03ad3487-252d-4605-bd1d-c9344a30d37f.jpg)![20220618_235020.jpg](https://user-images.githubusercontent.com/85219784/174446709-bb279a94-27a6-4bb3-884b-957044b3989e.jpg)![20220618_235033.jpg](https://user-images.githubusercontent.com/85219784/174446713-975dd69a-5647-4e65-8058-29ca15fb7487.jpg)![20220618_235047.jpg](https://user-images.githubusercontent.com/85219784/174446716-4ae12a5c-563c-48bc-9877-c8629eb52b6d.jpg)![20220618_235102.jpg](https://user-images.githubusercontent.com/85219784/174446719-f123cf38-c4d7-4864-a106-4bba0ae4690f.jpg)![20220618_235109.jpg](https://user-images.githubusercontent.com/85219784/174446722-0df9ee28-f9c7-4cee-913a-ec0e3df2178a.jpg)![20220618_235112.jpg](https://user-images.githubusercontent.com/85219784/174446730-41987001-edee-4fa0-8667-776cceacef76.jpg)![20220618_235117.jpg](https://user-images.githubusercontent.com/85219784/174446731-70184982-f9c3-44fd-b438-305cadddfcb8.jpg)![20220618_235125.jpg](https://user-images.githubusercontent.com/85219784/174446734-7bb4761d-8237-4577-b6e1-f52fa1cc99e6.jpg)![20220618_235123.jpg](https://user-images.githubusercontent.com/85219784/174446733-11ced73c-b64f-4ee9-9cbc-f10e93f8f642.jpg)

**Comment by pizzamx** [comment]
看不懂了，应该是下载成功了（29018），但为啥后来又说不成功（28907），抱歉我浅薄的知识没法看明白，而且这一步似乎跟这个插件没关系了

**Comment by wjw054509** [comment]
字幕文件我是让其自动下载存储在我nas的文件夹，是否会是这个原因导致下载失败

**Comment by wjw054509** [comment]
> 字幕文件我是让其自动下载存储在我nas的文件夹，是否会是这个原因导致下载失败

果然是这个问题，换了存储字幕文件夹解决了
